# Logging Configuration for AutoML Text Classification Pipeline

logging:
  version: 1
  disable_existing_loggers: false

  formatters:
    console:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      datefmt: "%H:%M:%S"

    file:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"

    detailed:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(funcName)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"

  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: console
      stream: ext://sys.stdout

    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: file
      filename: logs/autotext.log
      maxBytes: 10485760 # 10MB
      backupCount: 5
      mode: a

  root:
    level: INFO
    handlers: [console, file]

# Log Management Settings
log_management:
  max_log_size_mb: 50
  max_total_log_files: 20
  cleanup_on_startup: true
  archive_old_logs: true
  log_retention_days: 30
